<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<OutputType>WinExe</OutputType>
		<ApplicationIcon>port.ico</ApplicationIcon>
		<UseWindowsForms>true</UseWindowsForms>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
		<FileVersion>1.0.1</FileVersion>
	</PropertyGroup>
	
	<ItemGroup>
		<Content Include="port.ico" />
		<PackageReference Include="SunHealth.Gateway.Services.WxWindows" Version="4.0.1" />
		<PackageReference Include="System.IO.Ports" Version="9.0.4" />
		<PackageReference Include="System.Management" Version="9.0.7" />
	</ItemGroup>
	
	<ItemGroup>
	  <ProjectReference Include="..\Common\Common.csproj" />
	</ItemGroup>
</Project>